import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Markdown from 'markdown-to-jsx'
import BlogModal from '../sections/components/blog-modal'
import Button from 'react-bootstrap/Button'

export default function Blog(props) {

  const [data, setData] = useState(props.data)
  const [isLoading, setLoading] = useState(false)
  const [posts, setPosts] = useState(null)

  useEffect(() => {
      setLoading(true)
      fetch('https://koleeum-admin.herokuapp.com/posts')
      .then((res) => res.json())
      .then((posts) => {
          setPosts(posts)
          setLoading(false)
      })
  }, [])

  if (isLoading) return <p>Loading...</p>
  if (!posts) return <p>No posts!</p>

  return (
    <div className="blog-page">
      <Head>
        <title>Se former - Koleeum.immo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog fadeIn">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h1 className="title">{data.title}</h1>
              <p className="description">{data.description}</p>
            </div>
          </div>
          <div className="row">
            <div className="col-12">
              <div className="cards">
                { posts.map(function(post) {
                  return ( 
                    <div key={post.title} className="card">
                      <div className="card-thumbnail">
                        <img src={post.image.url} />
                      </div>
                      <div className="card-txt">
                        <h3 className="card-title">{post.title}</h3>
                        <div className="card-description">{post.description}</div>
                        <BlogModal post={post} />
                      </div>
                    </div> 
                  )
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://koleeum-admin.herokuapp.com/blog')
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}