import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'

export default function Investisseurs(props) {

  const [data, setData] = useState(props.data)

  return (
    <div className="homepage">
      <Head>
        <title>Koleeum.immo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero">
        <h2>{data.title}</h2>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://koleeum-admin.herokuapp.com/proprietaires')
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}