import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Markdown from 'markdown-to-jsx'
import RegistrationForm from '../sections/components/registration-form'

export default function Investisseurs(props) {

  const [data, setData] = useState(props.data)

  return (
    <div className="investisseurs">
      <Head>
        <title>Koleeum.immo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="locataires fadeIn">
        <div className="container">
            <h1 className="title">{data.title}</h1>
            <Markdown options={{ wrapper: 'div', forceWrapper: true }} className="description">{data.description}</Markdown>
            <div className="sections">
                {data.page_sections.map((section) =>
                    <div key={section.id} className="section">
                        <div className="image">
                            <img src={section.image.url} />
                        </div>
                        <div className="txt-content">
                            <h1 className="title">{section.title}</h1>
                            <Markdown options={{ wrapper: 'div', forceWrapper: true }} className="description">{section.description}</Markdown>
                        </div>
                    </div>
                )}
            </div>
            <div className="choose-us">
                <div className="container">
                    <div className="image">
                        <img src={data.choose_us.image.url} />
                    </div>
                    <div className="text-content">
                        <h2 className="title">{data.choose_us.title}</h2>
                        <Markdown options={{ wrapper: 'div', forceWrapper: true }} className="description">{data.choose_us.description}</Markdown>
                        <div className="sections">
                            {data.choose_us.card.map((card) =>
                                <div key={card.id} className="section">
                                    <div className="icon">
                                        <img src={card.icon.url} />
                                    </div>
                                    <div className="txt-content">
                                        <h1 className="title">{card.title}</h1>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
            <div className="registration">
                <div className="container">
                    <h2 className="title">{data.registration.title}</h2>
                    <Markdown options={{ wrapper: 'div', forceWrapper: true }} className="description">{data.registration.description}</Markdown>
                    <RegistrationForm />
                </div>
            </div>
        </div>
    </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://koleeum-admin.herokuapp.com/locataires')
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}
